# Source: https://devcenter.heroku.com/articles/container-registry-and-runtime

name: Deploy Back End Stage To Heroku

on:
  push:
    branches:
      # Run jobs when updating or creating any branch except for main on GitHub.
      - "**"
      - "!main"
    # paths:
    # Re-run jobs when content changes in specified file or directory.
    #  - backend/**
    #  - .github/workflows/stage-backend.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Docker login"
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: docker login --username=_ --password=$(heroku auth:token) registry.heroku.com

      - name: "Build Docker Image"
        run: yarn run docker-start

      - name: "Tag docker image"
        run: docker tag node-starter registry.heroku.com/${{ secrets.HEROKU_STAGE_BACKEND }}/web

      - name: "Push docker image"
        run: docker push registry.heroku.com/${{ secrets.HEROKU_STAGE_BACKEND }}/web

      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push -a ${{ secrets.HEROKU_STAGE_BACKEND }} web

      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a ${{ secrets.HEROKU_STAGE_BACKEND }} web
